#!/bin/bash

WAYLAND_OPTS=""

if [ -n "$WAYLAND_DISPLAY" ] && [ -z "$DISABLE_WAYLAND" ]; then
  WAYLAND_OPTS="--enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer,UseOzonePlatform --ozone-platform-hint=auto"
fi
export LD_PRELOAD=$SNAP/getpwuid_stub.so
exec "$SNAP/lunarclient" --no-sandbox --disable-seccomp-filter-sandbox $WAYLAND_OPTS "$@"
