name: lunar-client
base: core24
version: 3.5.15
title: Lunar Client
summary: A modpack for all modern versions of Minecraft!
description: |
   Boosted frames, all the popular mods, multi OS support, and did we mention
   it’s completely free? So what are you waiting for - Download today!

grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:

contact: https://github.com/kenvandine/lunar-client/issues
issues: https://github.com/kenvandine/lunar-client/issues
website: https://www.lunarclient.com/
icon: icon.png

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  lunar-client:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      craftctl default
      wget -O lunar-client https://launcherupdates.lunarclientcdn.com/Lunar%20Client-$SNAPCRAFT_PROJECT_VERSION-ow.AppImage
      chmod a+x lunar-client
      ./lunar-client --appimage-extract
      chmod -R a+rX squashfs-root
      mv squashfs-root/* $CRAFT_PART_INSTALL/
      chmod 755 $CRAFT_PART_INSTALL/
      sed -i.bak -e 's|Icon=lunarclient$|Icon=${SNAP}/lunarclient.png|g' $CRAFT_PART_INSTALL/lunarclient.desktop
    prime:
      - -chrome-sandbox
      - -usr/lib

apps:
  lunar-client:
    extensions: [gnome]
    command: launcher
    desktop: lunarclient.desktop
    plugs:
      - home
      - network
      - audio-playback
      - shmem
    environment:
      HOME: $SNAP_USER_COMMON
      TMPDIR: $XDG_RUNTIME_DIR

plugs:
  shmem:
    interface: shared-memory
    private: true
  dot-minecraft:
    interface: personal-files
    write:
      - $HOME/.minecraft
  dot-lunarclient:
    interface: personal-files
    write:
      - $HOME/.lunarclient
