name: lunar-client
base: core24
version: 3.5.15
summary: Lunar Client
description: |
   Lunar Client

grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:

layout:
  /usr/bin/zenity:
    bind-file: $SNAP/usr/bin/zenity

parts:
  lunar-client:
    plugin: nil
    build-packages:
      - wget
    stage-packages:
      - zenity
    override-build: |
      craftctl default
      wget -O lunar-client https://launcherupdates.lunarclientcdn.com/Lunar%20Client-$SNAPCRAFT_PROJECT_VERSION-ow.AppImage
      chmod a+x lunar-client
      ./lunar-client --appimage-extract
      mv squashfs-root/* $CRAFT_PART_INSTALL/
    prime:
      - -usr/lib
      - -chrome-sandbox

apps:
  lunar-client:
    extensions: [gnome]
    command: AppRun --no-sandbox --disable-seccomp-filter-sandbox
    desktop: lunarclient.desktop
    plugs:
      - home
      - network
      - audio-playback
      - shmem
    environment:
      HOME: $SNAP_USER_COMMON
      TMPDIR: $XDG_RUNTIME_DIR
      DISABLE_WAYLAND: 1
      APPDIR: $SNAP

plugs:
  shmem:
    interface: shared-memory
    private: true
